#!/bin/bash
function bootstrap_minecraft {
	local msm_dir="$plugindir/msm"
	if [ ! -e "$msm_dir" ]; then
		git clone 'git://github.com/marcuswhybrow/minecraft-server-manager.git' "$msm_dir"
	fi
	packages+=('default-jre-headless')
	packages+=('screen')
	packages+=('rsync')
	packages+=('zip')
	packages+=('bash-completion')
	insert_task_before $TASK_INITSCRIPTS "$plugindir/tasks/install-msm"
}

bootstrap_minecraft
