#!/bin/bash
function bootstrap_minecraft {
	git clone 'git://github.com/marcuswhybrow/minecraft-server-manager.git' 'msm'
	packages+=('sun-java6-jre')
	packages+=('screen')
	packages+=('rsync')
	packages+=('zip')
	packages+=('bash-completion')
	insert_task_before $TASK_INITSCRIPTS "$plugindir/tasks/install-minecraft"
}

bootstrap_minecraft
