#!/bin/bash
### BEGIN INIT INFO
# Provides:       minecraft
# Required-Start: $remote_fs $network
# Required-Stop:  $remote_fs $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: starts the minecraft server
# Description:    starts the minecraft server
### END INIT INFO
# We depend on $remote_fs in case the minecraft installation
# is moved to a separate EBS volume

PATH=/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
SERVICE_NAME="Minecraft server"
USER="minecraft"
HOMEDIR="/usr/local/minecraft"
LOGFILE="/var/log/minecraft.log"
PIDFILE="/var/run/minecraft.pid"
DAEMON="$HOMEDIR/run_minecraft.sh"
DAEMONARGS=""

set -e

function start {
	printf "Starting $SERVICE_NAME: "
	
	if [ ! -f "$PIDFILE" ]; then
		touch "$PIDFILE"
		chown "$USER" "$PIDFILE"
	fi
	
	if [ ! -f "$LOGFILE" ]; then
	 touch "$LOGFILE"
	 chown "$USER:adm" "$LOGFILE"
	 chmod 0640 "$LOGFILE"
	fi
	
	start-stop-daemon \
		--start --quiet --make-pidfile --pidfile $PIDFILE --background \
		--chuid $USER --chdir $HOMEDIR \
		--exec $DAEMON -- $DAEMONARGS
	printf ".\n"
}

function stop {
	printf "Stopping $SERVICE_NAME: "
	
	start-stop-daemon --stop --quiet --pidfile $PIDFILE
	rm -f "$PIDFILE"
	printf ".\n"
}

function restart {
	stop
	start
}

case "$1" in
	start) start         ;;
	stop)  stop          ;;
	restart) stop; start ;;
  *)
		echo "Usage: $0 {start|stop|restart}" >&2
		exit 1
		;;
  esac
exit
